SELECT P.PRODUCT_CODE AS PRODUCT_CODE,
       SUM(P.PRICE * IFNULL(O.SALES_AMOUNT, 0)) AS SALES
  FROM PRODUCT P LEFT JOIN OFFLINE_SALE O
    ON P.PRODUCT_ID = O.PRODUCT_ID
 GROUP BY P.PRODUCT_CODE
 ORDER BY SALES DESC, PRODUCT_CODE ASC;