SELECT SUM(SCORE) AS SCORE,
       HE.EMP_NO,
       HE.EMP_NAME,
       HE.POSITION,
       HE.EMAIL
  FROM HR_EMPLOYEES HE
  JOIN HR_GRADE HG ON HE.EMP_NO = HG.EMP_NO
 GROUP BY YEAR, EMP_NO
 HAVING HG.YEAR = '2022'
 ORDER BY SCORE DESC
 LIMIT 1;